### ISSUE TITLE
Some notes from testing the sequencer

### ISSUE THREAD

**Issue by roeytsemah** [lucblender/simple_micro_easel#1]
- Add downloads list - Daisyduino toolchain, Adafruit_MPR121, Adafruit_MCP23X17 and Adafruit_NeoPixel
- When testing, remember to select the port, and press reset. Otherwise you won't see the serial monitor.

**NOTES REGARDING SERIAL MONITOR**
It's hard to read everything because 01. there are no line breaks and 02. the names used are not familiar to the builder (yet). When I solder pin 30 I don't yet know it's the clockRate.

Suggestion:
PIN 05 | SEQUENCER STEP 01 |  | [VALUE]
PIN 02 | SEQUENCER STEP 04 |  | [VALUE]
PIN 31 | CLOCK ClockRate | [VALUE]

This way I can quickly see the pin number I just soldered, and also learn that its purpose should be.

**Comment by lucblender** [comment]
Download list added in [c16408d](https://github.com/lucblender/simple_micro_easel/commit/c16408d2f4b285d88f85b63bf7efd1daa5d73d1a)

**Comment by lucblender** [comment]
Better serial monitor print for hardware test done in [3c604be](https://github.com/lucblender/simple_micro_easel/commit/3c604be670b2db8a3e721e3674064918693f3608)
