### ISSUE TITLE
Wiring of MUX

### ISSUE THREAD

**Issue by roeytsemah** [lucblender/simple_micro_easel#2]
- lines 129-141 should be commented in order to see the serial monitor
- Both SCL needs to be connected together so it's not pin 10 but pin 12
- Note that SCL might be called SCK
- make sure to connect the following mux pins (if not using the Adafruit breakout)
> VDD to VCC
- RESET to VCC
- SCL pullup and to daisy
- SDA pullup and to daisy
- A0, A1, A2 to GND
- VSS to GND
- INTA and INTB to daisy gpios
- GPIOA0..7 and GPIOB..7 to simple pins

- Suggest to build in three phases. Phase one until mux. Phase two mux. phase three touch
-

**Comment by lucblender** [comment]
Added GPIO expander pin in cheat sheet in [8d11b46](https://github.com/lucblender/simple_micro_easel/commit/8d11b4685dfd8aa6fe930af694f8d1d41865406e)
